
version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8000:8000"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - app-network

  tripmap:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tripmap.rule=PathPrefix(`/`)"
      - "traefik.http.routers.tripmap.entrypoints=web"
      - "traefik.http.services.tripmap.loadbalancer.server.port=3000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
